import { GitMoji } from "../types";

export const InitialGitMojis: GitMoji[] = [
  {
    emoji: "🎨",
    title: ":art:",
    description: "Improve structure / format of the code.",
    keywords: [],
  },
  {
    emoji: "⚡️",
    title: ":zap:",
    description: "Improve performance.",
    keywords: [],
  },
  {
    emoji: "🔥",
    title: ":fire:",
    description: "Remove code or files.",
    keywords: [],
  },
  {
    emoji: "🐛",
    title: ":bug:",
    description: "Fix a bug.",
    keywords: [],
  },
  {
    emoji: "🚑️",
    title: ":ambulance:",
    description: "Critical hotfix.",
    keywords: [],
  },
  {
    emoji: "✨",
    title: ":sparkles:",
    description: "Introduce new features.",
    keywords: [],
  },
  {
    emoji: "📝",
    title: ":memo:",
    description: "Add or update documentation.",
    keywords: [],
  },
  {
    emoji: "🚀",
    title: ":rocket:",
    description: "Deploy stuff.",
    keywords: [],
  },
  {
    emoji: "💄",
    title: ":lipstick:",
    description: "Add or update the UI and style files.",
    keywords: [],
  },
  {
    emoji: "🎉",
    title: ":tada:",
    description: "Begin a project.",
    keywords: [],
  },
  {
    emoji: "✅",
    title: ":white_check_mark:",
    description: "Add, update, or pass tests.",
    keywords: [],
  },
  {
    emoji: "🔒️",
    title: ":lock:",
    description: "Fix security issues.",
    keywords: [],
  },
  {
    emoji: "🔐",
    title: ":closed_lock_with_key:",
    description: "Add or update secrets.",
    keywords: [],
  },
  {
    emoji: "🔖",
    title: ":bookmark:",
    description: "Release / Version tags.",
    keywords: [],
  },
  {
    emoji: "🚨",
    title: ":rotating_light:",
    description: "Fix compiler / linter warnings.",
    keywords: [],
  },
  {
    emoji: "🚧",
    title: ":construction:",
    description: "Work in progress.",
    keywords: [],
  },
  {
    emoji: "💚",
    title: ":green_heart:",
    description: "Fix CI Build.",
    keywords: [],
  },
  {
    emoji: "⬇️",
    title: ":arrow_down:",
    description: "Downgrade dependencies.",
    keywords: [],
  },
  {
    emoji: "⬆️",
    title: ":arrow_up:",
    description: "Upgrade dependencies.",
    keywords: [],
  },
  {
    emoji: "📌",
    title: ":pushpin:",
    description: "Pin dependencies to specific versions.",
    keywords: [],
  },
  {
    emoji: "👷",
    title: ":construction_worker:",
    description: "Add or update CI build system.",
    keywords: [],
  },
  {
    emoji: "📈",
    title: ":chart_with_upwards_trend:",
    description: "Add or update analytics or track code.",
    keywords: [],
  },
  {
    emoji: "♻️",
    title: ":recycle:",
    description: "Refactor code.",
    keywords: [],
  },
  {
    emoji: "➕",
    title: ":heavy_plus_sign:",
    description: "Add a dependency.",
    keywords: [],
  },
  {
    emoji: "➖",
    title: ":heavy_minus_sign:",
    description: "Remove a dependency.",
    keywords: [],
  },
  {
    emoji: "🔧",
    title: ":wrench:",
    description: "Add or update configuration files.",
    keywords: [],
  },
  {
    emoji: "🔨",
    title: ":hammer:",
    description: "Add or update development scripts.",
    keywords: [],
  },
  {
    emoji: "🌐",
    title: ":globe_with_meridians:",
    description: "Internationalization and localization.",
    keywords: [],
  },
  {
    emoji: "✏️",
    title: ":pencil2:",
    description: "Fix typos.",
    keywords: [],
  },
  {
    emoji: "💩",
    title: ":poop:",
    description: "Write bad code that needs to be improved.",
    keywords: [],
  },
  {
    emoji: "⏪️",
    title: ":rewind:",
    description: "Revert changes.",
    keywords: [],
  },
  {
    emoji: "🔀",
    title: ":twisted_rightwards_arrows:",
    description: "Merge branches.",
    keywords: [],
  },
  {
    emoji: "📦️",
    title: ":package:",
    description: "Add or update compiled files or packages.",
    keywords: [],
  },
  {
    emoji: "👽️",
    title: ":alien:",
    description: "Update code due to external API changes.",
    keywords: [],
  },
  {
    emoji: "🚚",
    title: ":truck:",
    description: "Move or rename resources (e.g.: files, paths, routes).",
    keywords: [],
  },
  {
    emoji: "📄",
    title: ":page_facing_up:",
    description: "Add or update license.",
    keywords: [],
  },
  {
    emoji: "💥",
    title: ":boom:",
    description: "Introduce breaking changes.",
    keywords: [],
  },
  {
    emoji: "🍱",
    title: ":bento:",
    description: "Add or update assets.",
    keywords: [],
  },
  {
    emoji: "♿️",
    title: ":wheelchair:",
    description: "Improve accessibility.",
    keywords: [],
  },
  {
    emoji: "💡",
    title: ":bulb:",
    description: "Add or update comments in source code.",
    keywords: [],
  },
  {
    emoji: "🍻",
    title: ":beers:",
    description: "Write code drunkenly.",
    keywords: [],
  },
  {
    emoji: "💬",
    title: ":speech_balloon:",
    description: "Add or update text and literals.",
    keywords: [],
  },
  {
    emoji: "🗃️",
    title: ":card_file_box:",
    description: "Perform database related changes.",
    keywords: [],
  },
  {
    emoji: "🔊",
    title: ":loud_sound:",
    description: "Add or update logs.",
    keywords: [],
  },
  {
    emoji: "🔇",
    title: ":mute:",
    description: "Remove logs.",
    keywords: [],
  },
  {
    emoji: "👥",
    title: ":busts_in_silhouette:",
    description: "Add or update contributor(s).",
    keywords: [],
  },
  {
    emoji: "🚸",
    title: ":children_crossing:",
    description: "Improve user experience / usability.",
    keywords: [],
  },
  {
    emoji: "🏗️",
    title: ":building_construction:",
    description: "Make architectural changes.",
    keywords: [],
  },
  {
    emoji: "📱",
    title: ":iphone:",
    description: "Work on responsive design.",
    keywords: [],
  },
  {
    emoji: "🤡",
    title: ":clown_face:",
    description: "Mock things.",
    keywords: [],
  },
  {
    emoji: "🥚",
    title: ":egg:",
    description: "Add or update an easter egg.",
    keywords: [],
  },
  {
    emoji: "🙈",
    title: ":see_no_evil:",
    description: "Add or update a .gitignore file.",
    keywords: [],
  },
  {
    emoji: "📸",
    title: ":camera_flash:",
    description: "Add or update snapshots.",
    keywords: [],
  },
  {
    emoji: "⚗️",
    title: ":alembic:",
    description: "Perform experiments.",
    keywords: [],
  },
  {
    emoji: "🔍️",
    title: ":mag:",
    description: "Improve SEO.",
    keywords: [],
  },
  {
    emoji: "🏷️",
    title: ":label:",
    description: "Add or update types.",
    keywords: [],
  },
  {
    emoji: "🌱",
    title: ":seedling:",
    description: "Add or update seed files.",
    keywords: [],
  },
  {
    emoji: "🚩",
    title: ":triangular_flag_on_post:",
    description: "Add, update, or remove feature flags.",
    keywords: [],
  },
  {
    emoji: "🥅",
    title: ":goal_net:",
    description: "Catch errors.",
    keywords: [],
  },
  {
    emoji: "💫",
    title: ":dizzy:",
    description: "Add or update animations and transitions.",
    keywords: [],
  },
  {
    emoji: "🗑️",
    title: ":wastebasket:",
    description: "Deprecate code that needs to be cleaned up.",
    keywords: [],
  },
  {
    emoji: "🛂",
    title: ":passport_control:",
    description: "Work on code related to authorization, roles and permissions.",
    keywords: [],
  },
  {
    emoji: "🩹",
    title: ":adhesive_bandage:",
    description: "Simple fix for a non-critical issue.",
    keywords: [],
  },
  {
    emoji: "🧐",
    title: ":monocle_face:",
    description: "Data exploration/inspection.",
    keywords: [],
  },
  {
    emoji: "⚰️",
    title: ":coffin:",
    description: "Remove dead code.",
    keywords: [],
  },
  {
    emoji: "🧪",
    title: ":test_tube:",
    description: "Add a failing test.",
    keywords: [],
  },
  {
    emoji: "👔",
    title: ":necktie:",
    description: "Add or update business logic.",
    keywords: [],
  },
  {
    emoji: "🩺",
    title: ":stethoscope:",
    description: "Add or update healthcheck.",
    keywords: [],
  },
  {
    emoji: "🧱",
    title: ":bricks:",
    description: "Infrastructure related changes.",
    keywords: [],
  },
  {
    emoji: "🧑‍💻",
    title: ":technologist:",
    description: "Improve developer experience.",
    keywords: [],
  },
  {
    emoji: "💸",
    title: ":money_with_wings:",
    description: "Add sponsorships or money related infrastructure.",
    keywords: [],
  },
  {
    emoji: "🧵",
    title: ":thread:",
    description: "Add or update code related to multithreading or concurrency.",
    keywords: [],
  },
  {
    emoji: "🦺",
    title: ":safety_vest:",
    description: "Add or update code related to validation.",
    keywords: [],
  },
];
